# syntax=docker/dockerfile:1

FROM node:20-alpine AS build
WORKDIR /web
RUN apk add --no-cache python3 make g++
COPY web/package.json web/package-lock.json ./
RUN npm ci || npm install
COPY web ./
RUN npm run build

FROM nginx:1.27-alpine AS runtime
WORKDIR /usr/share/nginx/html
COPY --from=build /web/dist ./
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]


